version: 0.2

phases:
  build:
    commands:
      - make qa-plan

artifacts:
  files:
    - build/infrastructure/api-primary/plan.txt
    - build/infrastructure/core-primary/plan.txt
    - build/infrastructure/core-secondary/plan.txt
    - build/infrastructure/storage/plan.txt
