version: 0.2

env:
  variables:
    RELEASE_BUCKET: release.ccna-int.deployment.ccna-int.ccna.info/platform

phases:
  build:
    commands:
      - make -j -O build

artifacts:
  files:
    - storage.tar.gz
    - core.tar.gz
    - api.tar.gz
    - config/**/*
    - project-settings.json
    - buildspec-qa-plan.yml
    - buildspec-qa-deploy.yml
    - buildspec-uat-plan.yml
    - buildspec-uat-deploy.yml
    - buildspec-prod-plan.yml
    - buildspec-prod-deploy.yml
    - platform-version.json
    - Makefile
